name: deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: gcp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run build
      - uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --exclude='/.env' --exclude='/config.json' --exclude='/.credentials.json'
          remote_path: ~/twitch-sub-tracker/
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USERNAME }}
          remote_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
      - uses: appleboy/ssh-action@v1.0.3
        with: 
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          script: scripts/restart-twitch-sub-tracker.sh
