name: deploy
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: gcp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - run: npm ci
      - run: npm run build
      - run: npm prune --production
      - uses: up9cloud/action-rsync@v1.4
        env:
          HOST: ${{ vars.DEPLOY_HOST }}
          PORT: ${{ vars.DEPLOY_PORT }}
          USER: ${{ vars.DEPLOY_USER }}
          KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          TARGET: twitch-sub-tracker/
          ARGS_MORE: --exclude '/.env' --exclude='/config.json' --exclude='/.credentials.json' --chmod=Fu=rwx
          POST_SCRIPT: sudo systemctl restart twitch-sub-tracker.service
